modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="multmod"
version="1.0.0"
displayName="MultMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="opbes, MCreator"

[[dependencies.multmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




